In [2]:
!pip install numpy

In [3]:
import numpy as np

In [4]:
marks = [10, 20, 30]

In [5]:
marks*2

[10, 20, 30, 10, 20, 30]

In [6]:
marks+[2]

[10, 20, 30, 2]

In [7]:
type(marks)

list

In [8]:
arr = np.array([marks])
arr

array([[10, 20, 30]])

In [9]:
type(arr)

numpy.ndarray

In [10]:
arr*2

array([[20, 40, 60]])

In [ ]:
arr+2

array([[12, 22, 32]])

In [11]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [12]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In [13]:
np.arange(10, 20, 1.5)

array([10. , 11.5, 13. , 14.5, 16. , 17.5, 19. ])

In [14]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [15]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [16]:
lst = list(range(1, 10))
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
%timeit [i**2 for i in lst]

841 ns ± 7.95 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [18]:
arr = np.array(lst)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
%timeit arr**2

1.03 μs ± 16.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [20]:
arr = np.arange(10, 25)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
arr[0]

np.int64(10)

In [22]:
arr[-1]

np.int64(24)

In [23]:
arr[3:7]

array([13, 14, 15, 16])

In [24]:
np.array([10, 20, 30, 40.0])

array([10., 20., 30., 40.])

In [25]:
arr[1] = 110

In [26]:
arr

array([ 10, 110,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24])

### 2D List

In [27]:
lst2d = [[1, 2, 3], [4, 5, 6]]
lst2d

[[1, 2, 3], [4, 5, 6]]

In [28]:
arr2d = np.array(lst2d)
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
arr2d*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [30]:
arr2d+2

array([[3, 4, 5],
       [6, 7, 8]])

In [31]:
arr2d**2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [32]:
arr2d.size

6

In [33]:
arr2d.shape

(2, 3)

In [34]:
arr2d.ndim

2

In [35]:
arr2d[1][1]

np.int64(5)

In [36]:
arr2d[1, 1]

np.int64(5)

In [37]:
arr

array([ 10, 110,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24])

In [38]:
arr.ndim

1

In [39]:
arr.shape

(15,)

In [41]:
np.array([1, 2])

array([1, 2])

In [48]:
temp = np.array([[1, 2]])
temp

array([[1, 2]])

In [47]:
temp.shape

(1, 1, 2)